// packages/svelte/src/hooks/useConnect.tsx
import { readable } from 'svelte/store'
import { subW3, getW3, connectW3, disconnectW3, Injected } from '@w3vm/core'

type Status = "Initializing" | "Connecting" | "Disconnecting" | "Loading" | "GeneratingURI" | undefined

export function useConnect(){
  const connectors = readable<Injected[]>(getW3.connectors(),subW3.connectors)
  const status = readable<Status>(getW3.status(),subW3.status)
  return { connectors, connectW3, disconnectW3, status }
}

// packages/react/src/hooks/useConnect.tsx
import { useSyncExternalStore } from 'react'
import { subW3, getW3, connectW3, disconnectW3 } from '@w3vm/core'

export function useConnect(){
  const connectors = useSyncExternalStore(subW3.connectors, getW3.connectors, getW3.connectors)
  const status = useSyncExternalStore(subW3.status, getW3.status, getW3.status)
  return { connectors, connectW3, disconnectW3, status }
}
